[package]
name = "p12"
version = "0.3.1"
authors = ["hjiayz <hjiayz@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition = "2018"
keywords = ["pkcs12", "pkcs"]
description = "pure rust pkcs12 tool"
homepage = "https://github.com/Keruspe/pkcs-12"
repository = "https://github.com/Keruspe/pkcs-12"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4.0"
getrandom = "0.2.0"
block-modes = "0.8.0"
hmac = "0.11.0"
sha-1 = "0.9.1"
rc2 = "0.7.0"
des = "0.7.0"

[dependencies.yasna]
version = "0.4.0"
features = ["std"]

[dev-dependencies]
hex = "0.4.2"
hex-literal = "0.3.1"
