[package]
name = "p12"
version = "0.4.0"
authors = ["hjiayz <hjiayz@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition = "2018"
keywords = ["pkcs12", "pkcs"]
description = "pure rust pkcs12 tool"
homepage = "https://github.com/hjiayz/p12"
repository = "https://github.com/hjiayz/p12"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
block-modes = "^0.8"
des = "^0.7"
getrandom = "^0.2"
hmac = "^0.12"
lazy_static = "^1.4"
rc2 = "^0.7"
sha-1 = "^0.10"

[dependencies.yasna]
version = "^0.4"
features = ["std"]

[dev-dependencies]
hex = "^0.4.2"
hex-literal = "^0.3.1"
